modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://github.com/raoulvdberge/refinedstorage"
[[mods]]
modId="refinedstorage"
version="${version}"
displayName="Refined Storage"
updateJSONURL="https://refinedstorage.raoulvdberge.com/update"
displayURL="https://refinedstorage.raoulvdberge.com"
logoFile="logo.png"
authors="Refined Storage authors"
description='''
An elegant solution to your hoarding problem
'''
