modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/refinedmods/refinedstorage"
license="MIT"
[[mods]]
modId="refinedstorage"
version="${version}"
displayName="Refined Storage"
updateJSONURL="https://refinedmods.com/refined-storage/update.json"
displayURL="https://refinedmods.com/refined-storage"
logoFile="logo.png"
authors = "Refined Mods"
description = '''
An elegant solution to your hoarding problem
'''
