blank_issues_enabled: false
contact_links:
    - name: Discord Community Support
      url: https://discordapp.com/invite/VYzsydb
      about: Please ask and answer questions here. Issues should be used for bugs and feature requests.
