name: Validate changelog
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]
jobs:
  validate-changelog:
    uses: refinedmods/refinedarchitect/.github/workflows/validate-changelog.yml@v0.7.1